POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "u_name": "Nancy Drew2",
    "email": "drewyujy1y@gmail.com",
    "password": "1234nd"
}



###
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
     "email": "drewyujy1y@gmail.com",
    "password": "1234nd"
}

###
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
     "email": "drewyujyy@gmail.com",
    "password": "1234nd"
}

###
POST http://localhost:3000/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiIwYTM1MzQzYi01ZjM5LTQwNWEtYmU0MC1kNzg5ZThmMzRlZjciLCJzdWJqZWN0IjoiTmFuY3kgRHJldzIiLCJpZCI6dHJ1ZSwiaWF0IjoxNjkyNzAzMzA1LCJleHAiOjE2OTQzMzM5ODR9.NLGTNmk7Oxk6xPe2hbK9mQd2TkTyzoUDnBtA7bIgIzQ

{
    "product_name": "SonyBravia",
    "product_description": "cool screen blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah",
    "price": 300,
    "product_quantity": 3,
    "product_category": "Cosmetics",
    "product_image": "https://imgs.search.brave.com/JCAbYNrwsZ5K_xRKYYs1OGcOQBNosEPViX-20Ua8GIk/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9waXNj/ZXMuYmJ5c3RhdGlj/LmNvbS9pbWFnZTIv/QmVzdEJ1eV9VUy9p/bWFnZXMvcHJvZHVj/dHMvNjUwMS82NTAx/NTQzX3NkLmpwZztt/YXhIZWlnaHQ9MjAw/O21heFdpZHRoPTMw/MA"
}


###
GET http://localhost:3000/api/product


###
GET http://localhost:3000/api/product?PageNumber=5?PageSize=1



# GET PRODUCT BY ID
###
GET http://localhost:3000/api/product/92419e82-c148-46cf-9c01-e04f2cd708fb

###
DELETE http://localhost:3000/api/product/0c6e7662-0355-4533-9376-35044b9ced3b



###
PATCH  http://localhost:3000/api/product/92419e82-c148-46cf-9c01-e04f2cd708fb
Content-Type: application/json

{
    "product_name": "SonyBravia",
    "product_description": "cool screen blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah",
    "price": 300,
    "product_quantity": 3,
    "product_category": "Electronics",
    "product_image": "https://imgs.search.brave.com/JCAbYNrwsZ5K_xRKYYs1OGcOQBNosEPViX-20Ua8GIk/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9waXNj/ZXMuYmJ5c3RhdGlj/LmNvbS9pbWFnZTIv/QmVzdEJ1eV9VUy9p/bWFnZXMvcHJvZHVj/dHMvNjUwMS82NTAx/NTQzX3NkLmpwZztt/YXhIZWlnaHQ9MjAw/O21heFdpZHRoPTMw/MA"
}


###
POST http://localhost:3000/api/product/upload
Content-Type: multipart/form-data

{
    
}


# SEARCH FOR A PRODUCT BY NAME OR CATEGORY
###
GET http://localhost:3000/api/product/search/electronic




# CART ENDPOINTS
# EMPTY CART
###
POST http://localhost:3000/api/cart/items



# GET ITEMS IN THE CART
###
GET http://localhost:3000/api/cart/items

# ADD ITEM TO CART
###
POST http://localhost:3000/api/cart
Content-Type: application/json

{
    "product_id": "92419e82-c148-46cf-9c01-e04f2cd708fb",
    "product_quantity": 1
}


# REMOVE ITEM FROM CART
###
POST http://localhost:3000/api/cart/items/92419e82-c148-46cf-9c01-e04f2cd708fb
Content-Type: application/json

{
    "quantity":1
}